name: build
on: push
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/setup-node@lastest
                with:
                    node-version: 16
            -   run: npm install
            -   run: npm run build

